spring:
  datasource:
    url: jdbc:h2:file:/data/db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json