spring:
  datasource:
    url: jdbc:h2:file:/data/db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  
security:
  jwt:
    token:
      secret-key: 2394eeac9fc3db56189a894e221220b6089e78d3 
      expire-length: 36000000

app:
  domain.game.totalAttempts: 3
  provider.movies.imbdTopMoviesUrl: https://www.imdb.com/chart/top